version: '3.1'

services:
  nginx:
    build:
        context: .
        dockerfile: nginx.dockerfile
    ports:
        - 80:80
    volumes:
        - ./application:/var/www/application
    depends_on:
        - api

  api:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
    - ./application:/var/www/application
    depends_on:
      - db

  db:
    image: mariadb
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - dbvolume:/var/lib/mysql

volumes:   
    dbvolume:
